apiVersion: v1
kind: Service
metadata:
  name: node-demo-service
  namespace: default
  labels:
    app: node-demo
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: node-demo